import '../models/workout_day.dart';

final List<WorkoutDay> hiitProgram = [
  WorkoutDay(day: 1, title: "Full Body", isRestDay: false, exercises: ["Pompes", "Squats", "Burpees"]),
  WorkoutDay(day: 2, title: "Bas du corps", isRestDay: false, exercises: ["Fentes", "Squats", "Mountain Climbers"]),
  WorkoutDay(day: 3, title: "Repos", isRestDay: true, exercises: []),
  WorkoutDay(day: 4, title: "Haut du corps", isRestDay: false, exercises: ["Pompes", "Dips", "Planche"]),
  WorkoutDay(day: 5, title: "Cardio", isRestDay: false, exercises: ["Jumping Jacks", "Burpees", "High Knees"]),
  WorkoutDay(day: 6, title: "Repos", isRestDay: true, exercises: []),
  WorkoutDay(day: 7, title: "Full Body", isRestDay: false, exercises: ["Pompes", "Squats", "Burpees"]),
  WorkoutDay(day: 8, title: "Bas du corps", isRestDay: false, exercises: ["Fentes", "Squats", "Mountain Climbers"]),
  WorkoutDay(day: 9, title: "Repos", isRestDay: true, exercises: []),
  WorkoutDay(day: 10, title: "Haut du corps", isRestDay: false, exercises: ["Pompes", "Dips", "Planche"]),
  WorkoutDay(day: 11, title: "Cardio", isRestDay: false, exercises: ["Jumping Jacks", "Burpees", "High Knees"]),
  WorkoutDay(day: 12, title: "Repos", isRestDay: true, exercises: []),
  WorkoutDay(day: 13, title: "Full Body", isRestDay: false, exercises: ["Pompes", "Squats", "Burpees"]),
  WorkoutDay(day: 14, title: "Bas du corps", isRestDay: false, exercises: ["Fentes", "Squats", "Mountain Climbers"]),
  WorkoutDay(day: 15, title: "Repos", isRestDay: true, exercises: []),
  WorkoutDay(day: 16, title: "Haut du corps", isRestDay: false, exercises: ["Pompes", "Dips", "Planche"]),
  WorkoutDay(day: 17, title: "Cardio", isRestDay: false, exercises: ["Jumping Jacks", "Burpees", "High Knees"]),
  WorkoutDay(day: 18, title: "Repos", isRestDay: true, exercises: []),
  WorkoutDay(day: 19, title: "Full Body", isRestDay: false, exercises: ["Pompes", "Squats", "Burpees"]),
  WorkoutDay(day: 20, title: "Bas du corps", isRestDay: false, exercises: ["Fentes", "Squats", "Mountain Climbers"]),
  WorkoutDay(day: 21, title: "Repos", isRestDay: true, exercises: []),
  WorkoutDay(day: 22, title: "Haut du corps", isRestDay: false, exercises: ["Pompes", "Dips", "Planche"]),
  WorkoutDay(day: 23, title: "Cardio", isRestDay: false, exercises: ["Jumping Jacks", "Burpees", "High Knees"]),
  WorkoutDay(day: 24, title: "Repos", isRestDay: true, exercises: []),
  WorkoutDay(day: 25, title: "Full Body", isRestDay: false, exercises: ["Pompes", "Squats", "Burpees"]),
  WorkoutDay(day: 26, title: "Bas du corps", isRestDay: false, exercises: ["Fentes", "Squats", "Mountain Climbers"]),
  WorkoutDay(day: 27, title: "Repos", isRestDay: true, exercises: []),
  WorkoutDay(day: 28, title: "Haut du corps", isRestDay: false, exercises: ["Pompes", "Dips", "Planche"]),
  WorkoutDay(day: 29, title: "Cardio", isRestDay: false, exercises: ["Jumping Jacks", "Burpees", "High Knees"]),
  WorkoutDay(day: 30, title: "Repos", isRestDay: true, exercises: []),
];